openapi: 3.0.3
info:
  version: 1.0.0
  title: Music Player
  description: Descrição
  termsOfService: Termos de Serviço
servers:
  - url: http://localhost:8080/
    description: Localhost
paths:
  /list:
    get:
      summary: Lista arquivos de audio disponíveis
      responses:
        '200':
          description: Success
  /musicas/{id}:
    get:
      summary: Envia a musica selecionada
      responses:
        '200':
          description: Success
  
  /version:
    get:
      summary: Mostra versão do projeto do package.json
      responses:
        '200':
          description: Success